<?php
/**
 * Implements hook_user_login().
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Drupal\redirect\Entity\Redirect;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\node\NodeStorageInterface;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\HttpFoundation\JsonResponse;
use Drupal\taxonomy\Entity\Term; 
use Drupal\Core\Database\Connection;
use Drupal\Core\Entity\EntityTypeManager;


use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;

use Symfony\Component\HttpFoundation\Response;

/**
 * Implements hook_page_attachments().
 */
function webformolsys_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'webformolsys/webformolsys';
}

